export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-slate-950 px-6 py-12 text-slate-200">
      <div className="mx-auto max-w-4xl">
        <h1 className="mb-6 text-4xl font-bold text-white">Disclaimer</h1>

        <div className="space-y-6 text-sm leading-7">
          <p>
            Rental Deal Screener is intended solely for informational,
            educational, preliminary investment screening, rental property
            underwriting review, and real estate analysis purposes.
          </p>

          <section>
            <h2 className="mb-2 text-xl font-semibold text-white">
              No Professional Advice
            </h2>
            <p>
              Nothing on this platform constitutes financial, legal, tax,
              lending, brokerage, appraisal, accounting, investment, or other
              professional advice.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-xl font-semibold text-white">
              No Guarantee of Results
            </h2>
            <p>
              Investment performance, rental income, appreciation, occupancy,
              financing approval, lending outcomes, property values, cash flow,
              profitability, and financial outcomes are not guaranteed.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-xl font-semibold text-white">
              User Responsibility
            </h2>
            <p>
              Users are responsible for independently verifying all property
              data, rents, assumptions, calculations, expenses, taxes,
              insurance costs, repair budgets, vacancy assumptions, HOA fees,
              financing terms, investment suitability, and business decisions
              with qualified professionals.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-xl font-semibold text-white">
              Estimates Only
            </h2>
            <p>
              Calculations, scores, rankings, projections, reports, exports,
              printed summaries, and other outputs generated by the platform
              are estimates only and should not be relied upon as guarantees,
              professional underwriting, lending approval, appraisal opinions,
              or investment recommendations.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-xl font-semibold text-white">
              Data and Input Accuracy
            </h2>
            <p>
              Results depend on user-supplied data and assumptions. Rental Deal
              Screener does not guarantee that uploaded CSV data, property
              information, rent assumptions, expense assumptions, or financing
              assumptions are accurate, complete, current, or suitable for any
              particular purpose.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-xl font-semibold text-white">
              Limitation of Reliance
            </h2>
            <p>
              Users should not make financial, lending, acquisition,
              disposition, brokerage, tax, legal, or investment decisions based
              solely on platform outputs. Users should conduct independent due
              diligence and consult qualified professionals before making real
              estate or financial decisions.
            </p>
          </section>

          <p className="pt-6 text-slate-400">
            Last updated: June 2026
          </p>
        </div>
      </div>
    </div>
  );
}