export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-slate-950 px-6 py-12 text-slate-200">
      <div className="mx-auto max-w-4xl">
        <h1 className="mb-6 text-4xl font-bold text-white">Disclaimer</h1>

        <div className="space-y-6 text-sm leading-7">
          <p>
            Rental Deal Screener is intended solely for informational,
            educational, and preliminary real estate investment analysis
            purposes.
          </p>

          <section>
            <h2 className="mb-2 text-xl font-semibold text-white">
              No Financial Advice
            </h2>
            <p>
              Nothing on this platform constitutes financial, legal, tax,
              investment, or professional advice.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-xl font-semibold text-white">
              No Guarantee of Results
            </h2>
            <p>
              Investment performance, rental income, appreciation, occupancy,
              and financial outcomes are not guaranteed.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-xl font-semibold text-white">
              User Responsibility
            </h2>
            <p>
              Users are responsible for independently verifying all property
              data, assumptions, calculations, expenses, financing terms, and
              investment decisions.
            </p>
          </section>

          <section>
            <h2 className="mb-2 text-xl font-semibold text-white">
              Estimates Only
            </h2>
            <p>
              Calculations, scores, rankings, and projections generated by the
              platform are estimates only and should not be relied upon as
              guarantees or professional underwriting.
            </p>
          </section>

          <p className="pt-6 text-slate-400">
            Last updated: 2026
          </p>
        </div>
      </div>
    </div>
  );
}